sudo : required
services:
- docker

before_install:
 - docker build -t yuechen-cynthia/multitest -f ./client/Dockerfile.dev ./client

script:
 - docker run yuechen-cynthia/multitest npm test -- --coverage

after_success:
  - docker build -t yuechen-cynthia/multi-client ./client
  - docker build -t yuechen-cynthia/multi-nginx ./nginx
  - docker build -t yuechen-cynthia/multi-server ./server
  - docker build -t yuechen-cynthia/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yuechen-cynthia/multi-client
  - docker push yuechen-cynthia/multi-nginx
  - docker push yuechen-cynthia/multi-server
  - docker push yuechen-cynthia/multi-worker
